[features]
seeds = false
[programs.localnet]
vyper_otc = "QRd16aFfip7CEaXZUMQva4p9YYaQSog3ncEDTLoZPsP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/giacomocavicchioli/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "mb9NrZKiC3ZYUutgGhXwwkAL6Jkvmu5WLDbxWRZ8L9U"
program = "./deps/vyper-core/target/deploy/vyper_core.so"

[[test.genesis]]
address = "FB7HErqohbgaVV21BRiiMTuiBpeUYT8Yw7Z6EdEL7FAG"
program = "./deps/vyper-core/target/deploy/rate_mock.so"

[[test.genesis]]
address = "8fSeRtFseNrjdf8quE2YELhuzLkHV7WEGRPA9Jz8xEVe"
program = "./deps/vyper-core/target/deploy/redeem_logic_vanilla_option.so"